export const restaurants = [
  {
    id: 1,
    name: 'Urban Dhaba',
    cuisine: 'Chinese, Mughlai, Sea Food, North Indian, Sichuan',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1200&q=90&fit=crop',
    slug: 'urban-dhaba',
    description: 'Experience authentic flavors from Chinese, Mughlai, Seafood, North Indian, and Sichuan cuisines. Established in 2017, Urban Dhaba offers a diverse culinary journey with comfortable dining arrangements and unique decor. Must try: Naan and Masala Papad.',
    openingHours: '11:00 AM - 12:00 AM',
    capacity: 'Casual Dining, Dhaba, Cocktail Bar',
    address: 'The Myriad Business Hotel, Opposite Indian Petrol Pump, Shanti Nagar, Sector 6, Mira Bhayandar Road, Mira Road East, Thane-401107, Maharashtra',
    highlights: [
      'Established in 2017',
      'Average cost for two: ₹750',
      'Delivery, Dine-in, Take Away available',
      'Live music performances',
      'Good ambiance with comfortable eating arrangements',
      'Must try: Naan, Masala Papad',
    ],
    menu: {
      appetizers: [
        { name: 'Tandoori Paneer Tikka', price: '₹450', description: 'Grilled cottage cheese with spices' },
        { name: 'Chicken 65', price: '₹480', description: 'Spicy fried chicken bites' },
        { name: 'Vegetable Samosa', price: '₹180', description: 'Crispy pastry with spiced vegetables' },
        { name: 'Masala Papad', price: '₹80', description: 'Crispy papad with spiced toppings (Must Try)' },
      ],
      mains: [
        { name: 'Butter Chicken', price: '₹650', description: 'Creamy tomato-based curry' },
        { name: 'Dal Makhani', price: '₹450', description: 'Slow-cooked black lentils' },
        { name: 'Biryani', price: '₹750', description: 'Fragrant basmati rice with spices' },
        { name: 'Naan', price: '₹60', description: 'Freshly baked tandoor bread (Must Try)' },
      ],
      desserts: [
        { name: 'Gulab Jamun', price: '₹250', description: 'Sweet milk dumplings in syrup' },
        { name: 'Kulfi', price: '₹280', description: 'Traditional Indian ice cream' },
      ],
    },
  },
  {
    id: 2,
    name: 'Coastal Sea Food',
    cuisine: 'North Indian, Chinese, Biryani',
    image: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=1200&q=90&fit=crop',
    slug: 'coastal-seafood',
    description: 'A delightful seafood restaurant offering North Indian, Chinese, and Biryani specialties. Experience fresh flavors with comfortable dining options. Average cost ₹950 for two (without alcohol).',
    openingHours: '11:00 AM - 11:00 PM',
    capacity: 'Booth seating, Indoor seating, Large group seating available',
    address: 'Sai Baba Nagar, Mira Bhayandar Road, Opposite Indian Oil Petrol Pump, Mira Road, Mumbai',
    highlights: [
      'Average cost ₹950 for two (without alcohol)',
      'Home delivery and takeaway available',
      'Full bar available',
      'Wheelchair accessible',
      'Kid friendly',
      'Stags allowed',
      'Less noisy ambiance',
      'Vegetarian friendly',
      'Booth and indoor seating',
      'Large group seating available',
    ],
    menu: {
      appetizers: [
        { name: 'Lobster Bisque', price: '₹850', description: 'Creamy soup with fresh lobster' },
        { name: 'Grilled Prawns', price: '₹750', description: 'Jumbo prawns with garlic butter' },
        { name: 'Fish Tacos', price: '₹550', description: 'Crispy fish with fresh salsa' },
      ],
      mains: [
        { name: 'Grilled Salmon', price: '₹1200', description: 'Atlantic salmon with herbs' },
        { name: 'Lobster Thermidor', price: '₹1800', description: 'Baked lobster with cheese' },
        { name: 'Seafood Platter', price: '₹2200', description: 'Assorted fresh seafood' },
        { name: 'Biryani', price: '₹650', description: 'Fragrant basmati rice with spices' },
      ],
      desserts: [
        { name: 'Key Lime Pie', price: '₹350', description: 'Tangy lime dessert' },
        { name: 'Chocolate Lava Cake', price: '₹380', description: 'Warm chocolate cake' },
      ],
    },
  },
  {
    id: 3,
    name: 'Winkingg Owl',
    cuisine: 'North Indian, Chinese, Continental, Kebab, Mexican, Bar Food, Fast Food, Beverage',
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=1200&q=90&fit=crop',
    slug: 'winking-owl',
    description: 'A vibrant lounge bar and restaurant offering diverse cuisines from North Indian to Continental, Chinese, Mexican, and more. Features full bar, comfortable booth and lounge seating, perfect for large groups. Average cost ₹1,900 for two (without alcohol).',
    openingHours: '11:00 AM - 12:00 AM',
    capacity: 'Lounge seating, Booth seating, Large group seating available',
    address: 'Mira-Sai Baba Nagar, Mira-Bhayander Road, Opposite Indian Oil Petrol Pump, Mira Road, Mumbai',
    highlights: [
      'Full bar available',
      'Average cost ₹1,900 for two (without alcohol)',
      '₹200 for a pint of beer',
      'Home delivery and takeaway available',
      'Wheelchair accessible',
      'Kid friendly',
      'Stags allowed',
      'Less noisy ambiance',
      'Vegetarian friendly',
      'Indoor seating with booth and lounge options',
    ],
    menu: {
      cocktails: [
        { name: 'Old Fashioned', price: '₹650', description: 'Whiskey, sugar, bitters' },
        { name: 'Mojito', price: '₹550', description: 'Rum, mint, lime, soda' },
        { name: 'Cosmopolitan', price: '₹600', description: 'Vodka, cranberry, lime' },
        { name: 'Beer (Pint)', price: '₹200', description: 'Fresh pint of beer' },
      ],
      tapas: [
        { name: 'Bruschetta', price: '₹380', description: 'Toasted bread with tomatoes' },
        { name: 'Chicken Wings', price: '₹450', description: 'Spicy buffalo wings' },
        { name: 'Cheese Platter', price: '₹650', description: 'Assorted cheeses and crackers' },
        { name: 'Fish Hot Garlic', price: '₹450', description: 'Spicy garlic fish preparation' },
        { name: 'Pattaya Chicken', price: '₹480', description: 'Thai-style chicken preparation' },
      ],
      mains: [
        { name: 'Sunny Side', price: '₹350', description: 'Signature dish' },
        { name: 'Cheesy Garlic Bread', price: '₹280', description: 'Garlic bread with cheese' },
        { name: 'Lasagna', price: '₹550', description: 'Layered pasta dish' },
      ],
      beverages: [
        { name: 'Thick Shake', price: '₹200', description: 'Creamy milkshake' },
      ],
      desserts: [
        { name: 'Tiramisu', price: '₹350', description: 'Classic Italian dessert' },
        { name: 'Churros', price: '₹320', description: 'Spanish fried dough' },
      ],
    },
  },
];
