export const roomTypes = [
    {
        id: '1',
        name: 'Deluxe Room',
        description: 'Refined comfort featuring modern essentials, perfect for short business stays or weekend getaways.',
        price: 4230,
        oldPrice: 5500,
        images: ['/rooms/deluxe.png', '/rooms/executive.png', '/rooms/superior.png'],
        amenities: ['Double Bed', 'High-speed WiFi', 'Smart TV', 'Air Conditioning', 'Safe', 'Mini Bar'],
        capacity: '2 Guests',
        size: '150 sq ft',
        highlights: ['Free Cancellation before 12:00 PM', 'Complimentary Breakfast', 'Sanitized Room'],
    },
    {
        id: '2',
        name: 'Executive Room',
        description: 'A spacious and sophisticated suite designed for the modern business traveler, featuring premium furnishings and enhanced comfort.',
        price: 5500,
        oldPrice: 7150,
        images: ['/rooms/executive.png', '/rooms/superior.png', '/rooms/deluxe.png'],
        amenities: ['King Bed', 'Separate Living Area', 'High-speed WiFi', 'Smart TV', 'Marble Bathroom', 'Work Desk'],
        capacity: '2-3 Guests',
        size: '200 sq ft',
        highlights: ['Free Cancellation before 12:00 PM', 'Buffet Breakfast Included', 'High Floor View'],
    },
    {
        id: '3',
        name: 'Superior Suite',
        description: 'Experience ultimate luxury with our Superior Suite, offering panoramic city views, opulent marble accents, and a grand king-sized bed.',
        price: 6800,
        oldPrice: 8840,
        images: ['/rooms/superior.png', '/rooms/executive.png', '/rooms/deluxe.png'],
        amenities: ['Grand King Bed', 'Living Room', 'Jacuzzi', 'Smart TV', 'Butler Service', 'Walk-in Closet'],
        capacity: '2-4 Guests',
        size: '250 sq ft',
        highlights: ['Free Cancellation anytime', 'All Meals Included', 'Private Jacuzzi', 'Personal Butler'],
    },
];
